Ext.define('Bloodbank.bloodbank.shared.com.model.healthcare.BloodRequestModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bloodRequestId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "numberofUnits",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "patientName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "requestedByDr",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "requestedbyHospital",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dateneededby",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "dispatchedtoPatientOnDT",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "bloodgroup",
          "reference": "BloodGroup",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});