Ext.define('Bloodbank.bloodbank.shared.com.model.healthcare.BloodHistoryModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bloodHistoryId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bloodinfo",
          "reference": "BloodInfo",
          "defaultValue": ""
     }, {
          "name": "collectedDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "expDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "bloodReport",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "isTested",
          "type": "boolean",
          "defaultValue": ""
     }, {
          "name": "noOfUnits",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "height",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "weight",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "temp",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bp",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "pulse",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "unitsOfBlood",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "clinicalInfo",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});