Ext.define('Bloodbank.bloodbank.shared.com.model.healthcare.RegisterACampModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "campId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "orgName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "rsnForCamp",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bloodBankName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "fromDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "campTime",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "expectedCnt",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "arrivedCnt",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "bledCnt",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "toDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "Address",
          "reference": "AddressModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});