Ext.define('Bloodbank.bloodbank.shared.com.model.healthcare.RegisterADonorModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "donorId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "dob",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "gender",
          "reference": "Gender",
          "defaultValue": ""
     }, {
          "name": "bloodgroup",
          "reference": "BloodGroup",
          "defaultValue": ""
     }, {
          "name": "phone",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "emailId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "lastDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "howOften",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "Address",
          "reference": "AddressModel"
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});