Ext.define('Surveyportal.surveyportal.shared.com.survey.model.healthcare.SurveyResultModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "surveyResultId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "surveyquestionid",
          "reference": "SurveyQuestion",
          "defaultValue": ""
     }, {
          "name": "surveyanswerid",
          "reference": "SurveyAnswer",
          "defaultValue": ""
     }, {
          "name": "contactId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "surveyDate",
          "type": "date",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});