DROP TABLE IF EXISTS `ast_RegisterACamp_T`;

CREATE TABLE `ast_RegisterACamp_T` ( `campId` VARCHAR(256) NOT NULL, `orgName` VARCHAR(256) NOT NULL, `rsnForCamp` VARCHAR(256) NOT NULL, `bloodBankName` VARCHAR(256) NOT NULL, `addressId` VARCHAR(64) NOT NULL, `fromDate` DATE NOT NULL, `campTime` VARCHAR(256) NOT NULL, `expectedCnt` INT(10) NOT NULL, `arrivedCnt` INT(10) NULL DEFAULT NULL, `bledCnt` INT(10) NULL DEFAULT NULL, `toDate` DATE NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` DATETIME NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATETIME NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`campId`));

