DROP TABLE IF EXISTS `ast_RegisterADonor_T`;

CREATE TABLE `ast_RegisterADonor_T` ( `donorId` VARCHAR(256) NOT NULL, `dName` VARCHAR(256) NOT NULL, `dob` DATE NOT NULL, `gender` VARCHAR(64) NOT NULL, `bloodGroup` VARCHAR(256) NOT NULL, `phone` VARCHAR(256) NOT NULL, `emailId` VARCHAR(256) NOT NULL, `addressId` VARCHAR(64) NOT NULL, `lastDate` DATE NULL DEFAULT NULL, `howOften` VARCHAR(256) NULL DEFAULT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` DATETIME NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATETIME NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`donorId`));

