DROP TABLE IF EXISTS `ast_BloodInfo_T`;

CREATE TABLE `ast_BloodInfo_T` ( `bInfoId` VARCHAR(256) NOT NULL, `collectedDate` DATE NOT NULL, `visitId` VARCHAR(256) NULL DEFAULT NULL, `expDate` DATE NULL DEFAULT NULL, `bloodReport` TEXT NULL DEFAULT NULL, `isTested` TINYINT(1) NULL DEFAULT '0', `noOfUnits` INT(10) NULL DEFAULT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` DATETIME NULL DEFAULT '1900-01-01', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` DATETIME NULL DEFAULT '1900-01-01', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`bInfoId`));

