Ext.define('Bloodbank.bloodbank.shared.com.model.healthcontext.FindByBloodGroupModel.FindByBloodGroupModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "dispatchedtoPatientOnDT",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "dateneededby",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "requestedbyHospital",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "requestedByDr",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "patientName",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "numberofUnits",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "bloodRequestId",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "bloodGrp",
          "type": "string",
          "defaultValue": ""
     }]
});